config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users
  
  resources :items
  
  resources :users
  resolve('profil') { [:users] }
  resources :orders, only: [:create, :new, :show]
  resources :carts, only: [:show, :update]
  resources :line_items, only: [:create, :update, :destroy]

  namespace :admin do
    root 'facade#index'
    resources :items
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    # Find the card molecule for the index page at /views/_index_card.html.erb
  end 

  def show
    # Find the molecult for the item show page at /views/_show_card.html.erb
  end 

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_buttons.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="row justify-content-around w-75 m-2">
      <button type="button" class="btn btn-primary">Primary</button>
      <button type="button" class="btn btn-secondary">Secondary</button>
      <button type="button" class="btn btn-success">Success</button>
      <button type="button" class="btn btn-info">Info</button>
      <button type="button" class="btn btn-warning">Warning</button>
      <button type="button" class="btn btn-danger">Danger</button>
    </div>
    <div class="row justify-content-around w-75 m-2">
      <button type="button" class="btn btn-outline-primary">Primary</button>
      <button type="button" class="btn btn-outline-secondary">Secondary</button>
      <button type="button" class="btn btn-outline-success">Success</button>
      <button type="button" class="btn btn-outline-info">Info</button>
      <button type="button" class="btn btn-outline-warning">Warning</button>
      <button type="button" class="btn btn-outline-danger">Danger</button>
    </div>

    <div class="row justify-content-around w-75 m-2">
      <button type="button" class="btn btn-primary btn-lg">Large button</button>
      <button type="button" class="btn btn-primary">Default button</button>
      <button type="button" class="btn btn-primary btn-sm">Small button</button>
    </div>
    
  </div>
</div>

app/views/static_pages/_forms.html.erb
<div class="container">
  <form class="m-3">
    <fieldset class="w-50 mx-auto">
      <legend class="text-center">Se connecter</legend>
      <div class="form-group">
        <label for="exampleInputEmail1">Votre email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entrer votre email">
        <small id="emailHelp" class="form-text text-muted">Nous ne partageons jamais votre email avec des tiers.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Mot de passe</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <div class="form-group">
        <label for="confirm_password">Confirmer le mot de passe</label>
        <input type="password" class="form-control" id="confirm_password" placeholder="Confirm Password">
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <input class="form-check-input" type="checkbox" value="" checked="">
          Se souvenir de moi
        </label>
      </div>
      <button type="submit" class="btn btn-primary d-flex mx-auto">Se connecter</button>
    </fieldset>
  </form>
  <hr class="w-25"/>

  <form class="m-3">
    <fieldset class="w-50 mx-auto">
      <legend class="text-center">Créer un compte</legend>
      <div class="form-group">
        <label for="first_name">Votre prénom</label>
        <input type="text" class="form-control" id="first_name" aria-describedby="emailHelp" placeholder="Enter email">
      </div>
      <div class="form-group">
        <label for="last_name">Votre nom</label>
        <input type="text" class="form-control" id="last_name" aria-describedby="emailHelp" placeholder="Enter email">
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Votre email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entrer votre email">
        <small id="emailHelp" class="form-text text-muted">Nous ne partageons jamais votre email avec des tiers.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Mot de passe</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <div class="form-group">
        <label for="confirm_password">Confirmer le mot de passe</label>
        <input type="password" class="form-control" id="confirm_password" placeholder="Confirm Password">
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <input class="form-check-input" type="checkbox" value="" checked="">
          Se souvenir de moi
        </label>
      </div>
      <button type="submit" class="btn btn-primary d-flex mx-auto">Se connecter</button>
    </fieldset>
  </form>
  <hr class="w-25"/>

  <form class="m-3">
    <h2 class="text-center" id="forgot">Mot de passe oublié?</h2>
    <fieldset class="w-50 mx-auto">
      <div class="form-group">
        <label for="exampleInputEmail1">Entrer votre email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entrer votre email">
      </div>
      <button type="submit" class="btn btn-primary d-flex mx-auto">Mot de passe oublié</button>
    </fieldset>
  </form>
  <hr class="w-25"/>

  <form class="m-3">
    <h2 class="text-center" id="new-password">Nouveau mot de passe</h2>
    <fieldset class="w-50 mx-auto">
      <div class="form-group">
        <label for="new-pass">Entrer votre nouveau mot de passe</label>
        <input type="password" class="form-control" id="new-pass" aria-describedby="password" placeholder="Mot de passe">
      </div>
      <div class="form-group">
        <label for="confirm-pass">Confirmer votre nouveau mot de passe</label>
        <input type="password" class="form-control" id="confirm-pass" aria-describedby="password" placeholder="Confirmer le nouveau">
      </div>
      <div class="form-group">
        <label for="last_pass">Confirmer le changement avec l'ancien mot de passe</label>
        <input type="password" class="form-control" id="last_pass" aria-describedby="password" placeholder="Ancien mot de passe">
      </div>
      <button type="submit" class="btn btn-primary d-flex mx-auto">Changer</button>
    </fieldset>
  </form>
</div>

app/views/static_pages/_index_card.html.erb
<!-- Index card -->

<!-- let's put them in a row and col lg-4 each so that there's 3 cards per row -->

<div class ="container">
  <div class="row">
    <% items.each do |item| %>
      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="card mb-3">
          <h3 class="card-header"><%= item.title %></h3>
          <%= image_tag  item.image_url, class: "d-block user-select-none img-fluid", width: "100%", height: "200" %>
          <div class="card-body">
            <p class="card-text"><%= truncate(item.description, length: 100) %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= item.price %></li>
          </ul>
          <div class="card-body">
            <li><%= link_to "Ajouter au panier", line_items_path(item_id: item.id), class: "btn btn-success", method: "post" %>
            <%= link_to "Voir les détails", item_path(item.id), class: "btn btn-outline-info" %></li>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/_user_profile.html.erb
<div class="row justify-content-center">
    <div class="card custom-card m-2 w-75 p-3">
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-4 d-flex justify-content-center">
          <%= image_tag "https://robohash.org/2.png?set=set2", alt: 'avatar', class: "img-thumbnail rounded" %>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-8">
          <p class="text-gray-dark pl-3 pt-2">Votre prénom : Non mentionné</p>
          <p class="text-gray-dark pl-3 pt-2">Votre nom : Non mentionné</p>
          
          <p class="text-muted pl-3 pt-2">Votre email : Non mentionné</p>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/_users.html.erb
<div class="container my-5 py-4">
  <%= render partial: 'user_profile' %>

  <div class="row justify-content-center">
    <button type="button" class="btn btn-primary m-2">Editer votre email</button>
    <button type="button" class="btn btn-primary m-2">Editer votre profil</button>
  </div>
</div>