config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users
  
  resources :items
  
  resources :users
  resolve('profil') { [:users] }
  resources :orders, only: [:create, :new, :show]
  resources :carts, only: [:show, :update]
  resources :line_items, only: [:create, :update, :destroy]

  namespace :admin do
    root 'facade#index'
    resources :items
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
  has_many :orders
  has_one :cart

  before_create :not_admin

  def has_first_name?
    self.first_name
  end

  def to_param
    "#{id}-mon-profil"
  end

  def not_admin
    self.is_admin = false
  end

  def is_admin?
    self.is_admin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user
  before_action :set_cart
  before_action :authenticate_user!           , except: [:create]
  before_action :redirect_user_if_not_author  , only: [:show, :edit, :update, :destroy]

  def show
    @orders = current_user.orders
  end 

  def create
    Cart.create(user_id: @user.id)
  end 

  def edit
  end 

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: "Vos informations ont bien été mises à jour"
    else
      render :edit
    end
  end 

  def destroy
    @user.destroy
    redirect_to @user, success: "Votre profil a bien été supprimé"
  end 

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

  def check_user
    @user = User.find(current_user.id)
  end

  def redirect_user_if_not_author
    user = User.find(params[:id])
    unless current_user.id == user.id
      flash[:danger] = "Vous n'êtes pas le propriétaire de ce compte !!"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Se connecter", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "S'inscrire", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Mot de passe oublié?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Je n'ai pas reçu d'instructions de confirmation?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Je n'ai pas reçu les instructions de déverrouillage?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Se connecter avec #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>