config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users
  
  resources :items
  
  resources :users
  resolve('profil') { [:users] }
  resources :orders, only: [:create, :new, :show]
  resources :carts, only: [:show, :update]
  resources :line_items, only: [:create, :update, :destroy]

  namespace :admin do
    root 'facade#index'
    resources :items
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
  has_many :orders
  has_one :cart

  before_create :not_admin

  def has_first_name?
    self.first_name
  end

  def to_param
    "#{id}-mon-profil"
  end

  def not_admin
    self.is_admin = false
  end

  def is_admin?
    self.is_admin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user
  before_action :set_cart
  before_action :authenticate_user!           , except: [:create]
  before_action :redirect_user_if_not_author  , only: [:show, :edit, :update, :destroy]

  def show
    @orders = current_user.orders
  end 

  def create
    Cart.create(user_id: @user.id)
  end 

  def edit
  end 

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: "Vos informations ont bien été mises à jour"
    else
      render :edit
    end
  end 

  def destroy
    @user.destroy
    redirect_to @user, success: "Votre profil a bien été supprimé"
  end 

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

  def check_user
    @user = User.find(current_user.id)
  end

  def redirect_user_if_not_author
    user = User.find(params[:id])
    unless current_user.id == user.id
      flash[:danger] = "Vous n'êtes pas le propriétaire de ce compte !!"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_order.html.erb
<div class="row border-bottom border-gray py-2 mb-2 mr-2">
  <div class="col-1">
    <%= index %>
  </div>
  <div class="col-3">
    <%= order.created_at.strftime('%Y/%m/%d') %>
  </div>
  <div class="col-2 small text-center">
    <%= order.number_of_items %>
  </div>
  <div class="col-3 small text-center">
    <%= order.total_price %> €
  </div>
  <div class="col-3 small text-center">
    <%= link_to  "Voir la commande", order, class:"btn btn-outline-info" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <h1 class="h3 mb-3 font-weight-normal text-center">Editez vos informations personnelles</h1>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>Prénom</label>
          <%= f.text_field :first_name, class: "form-control", :required => true %>
        </div>

        <div class="form-group">
          <label>Nom</label>
          <%= f.text_field :last_name, class: "form-control", :required => true %>
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-block btn-primary">Mettre à jour</button>
        </div>
      <% end %>  

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2 class="my-5 text-center">Mon profil</h2>

  <h4>Mon prénom</h4>
  <p><%= current_user.first_name %></p>
  <hr>

  <h4>Mon nom</h4>
  <p><%= current_user.last_name %></p>
  <hr>

  <h4>Mon email</h4>
  <p><%= current_user.email %></p>
  <hr>

  <h4>Mes commandes</h4>
  
  <% if @orders.count > 0%>
    <div class="bg-white rounded box-shadow">
      <div class="row border-bottom border-gray py-2 mb-2 mr-2">
        <div class="col-1">
          N°
        </div>
        <div class="col-3">
          Date de la commande
        </div>
        <div class="col-2 small text-center">
          Nombre d'articles
        </div>
        <div class="col-3 small text-center">
          Prix total
        </div>
        <div class="col-3 small text-center">
          Actions
        </div>
      </div>
      <% @orders.each_with_index do |order, i| %>
        <%= render 'order', order: order, index: i+1 %>
      <% end %>
    </div>
  <% else %>
    <p>Tu n'as encore passé aucune commande</p>
    <hr>
  <% end %>

  <br/><br/>

  <div class="text-center">
    <%= link_to "Editer email et mot de passe", edit_user_registration_path, class: "btn btn-outline-primary mx-2" %>
    <%= link_to "Éditer mon profil", edit_user_path(current_user.id), class: "btn btn-outline-primary mx-2" %><br/>
    <br>
    <%= link_to  "Page d'accueil", root_path, class: "btn btn-info" %>
  </div>


  <br/><br/>

</div>