config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users
  
  resources :items
  
  resources :users
  resolve('profil') { [:users] }
  resources :orders, only: [:create, :new, :show]
  resources :carts, only: [:show, :update]
  resources :line_items, only: [:create, :update, :destroy]

  namespace :admin do
    root 'facade#index'
    resources :items
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items

  def total_price
    total = 0
    self.line_items.each do |line_item|
      total += line_item.item.price * line_item.quantity
    end
    return total
  end

  def add_item(item)
    item = line_items.find_by(item_id: item)

    if item 
      item.quantity += 1
    else
      item = line_items.new(item: item)
    end 
    
    return item
  end
  
  def empty
    self.line_items.each do |line_item|
      line_item.destroy
    end
  end

  def number_of_items
    total = 0
    self.line_items.each do |line_item|
      total += line_item.quantity
    end
    total
  end 

  def to_param
    "#{id}-votre-panier"
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, :set_cart
  before_action :redirect_user_if_not_author

  def show
  end

  def update
    @cart.empty
    respond_to do |format|
      format.html {redirect_to @cart, notice: "Votre panier a bien été vidé !"}
      format.json {head :no_content}
      format.js {}
    end 
  end

  private

  def redirect_user_if_not_author
    cart = Cart.find(params[:id])
    unless current_user.id == cart.user_id
      flash[:danger] = "Vous n'êtes pas le propriétaire de ce panier !!"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_line_item.html.erb
<% item = line_item.item %>

<div class="row border-bottom border-gray mr-1" id="line-item-<%= line_item.id %>">
  <div class="col-1">
    <%= image_tag item.picture, class: "old p-1", alt: "cat picture" %>
    <%# <img src="https://images.pexels.com/photos/1103832/pexels-photo-1103832.jpeg?cs=srgb&dl=pexels-oliver-sj%C3%B6str%C3%B6m-1103832.jpg&fm=jpg" alt="" class="mr-2 rounded m-auto mr-2" style="width: 4vw; height: 4vw; object-fit: cover;"> %>
  </div>
  <div class="col-2 d-flex align-items-center">
    <p class="ml-3">
      <strong class="text-gray-dark"><%= item.title %></strong>
    </p>
  </div>
  
  <div class="col-9">
    <div class="row">
      <div class="col-3"></div>
      <div class="col-3 text-center">
        <%= item.price %> €
      </div>
      <div class="col-1 text-center">
        <%= line_item.quantity %>
      </div>
      <div class="col-3 text-center">
        <%= line_item.total %> €
      </div>
      <div class="col-2 text-center">
        <%= link_to line_item, class: "text-danger p-2", method: "delete", data: {confirm: "Êtes-vous sûr(e) ?", remote: true} do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<div class="container pt-3">

  <div class="row">
    <div class="col-8">
      <div class="rounded box-shadow">
        <h5 class="border-bottom border-gray pb-2 mb-0 mr-2" id="your-cart">Mon panier</h5>
        <%if @cart.line_items.count > 0%>
          <div class="row border-bottom border-gray py-2 mb-2 mr-2" id="column-titles">
            <div class="col-3"></div>
            <div class="col-9">
              <div class="row">
                <div class="col-3"></div>
                <div class="col-3 small text-center">
                  Prix à l'unité
                </div>
                <div class="col-1 small text-center">
                  Qté
                </div>
                <div class="col-3 small text-center">
                  Prix total
                </div>
                <div class="col-2 small text-center">
                  Actions
                </div>
              </div>
            </div>
          </div>
          <%= render partial: 'line_item', collection: @cart.line_items %>
        <% else %>
          <p class="pt-3">Votre panier est vide</p>
        <%end %>
      </div>
    </div>
    <div class="col-4">
      <h5 class="border-bottom border-gray pb-2 mb-0">Finaliser ma commande</h6>
      <p class="pt-3">Total TTC de ma commande : <span id="order-price"> <%= @cart.total_price%> </span> €</p>
      <% if @cart.line_items.count > 0 %>
        <%= link_to "Vider mon panier", @cart, class: "btn btn-outline-danger", id: "empty-cart", method: "put", data: { confirm: "Êtes-vous sûr(e) ?"} %>
        <%= link_to "Passer ma commande", new_order_path(@cart.id), class: "btn btn-success", id: "order-cart" %>
      <% end %>
      <p class="mt-2"><%= link_to "Continuer mes achats", root_path, class: "btn btn-outline-primary" %></p>
    </div>
  </div>
</div>

app/views/carts/update.js.erb
document.getElementById("badge-number").innerHTML = "<%= @cart.number_of_items %>";

<% @cart.line_items.each do |line_item| %>
  document.getElementById("line-item-<%= line_item.id %>").remove();
<% end %>

document.getElementById("empty-cart").remove();
document.getElementById("order-cart").remove();
document.getElementById("column-titles").remove();
document.getElementById("your-cart").insertAdjacentHTML("afterend", "<p class='pt-3'>Votre panier est vide</p>");

document.getElementById("order-price").innerHTML= "<%= @cart.total_price %>";